image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  script:
    - npm install
  only:
    - master

deploy:
  stage: deploy
  image: ruby:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master
