export const IMAGEN_CREATE_PROVIDER = 'IMAGEN_CREATE_PROVIDER';
export const IMAGEN_FIND_BY_ID_PROVIDER = 'IMAGEN_FIND_BY_ID_PROVIDER';
export const IMAGEN_DELETE_PROVIDER = 'IMAGEN_DELETE_PROVIDER';
export const IMAGEN_UPDATE_PROVIDER = 'IMAGEN_UPDATE_PROVIDER';

export const STOCK_CREATE_PROVIDER = 'STOCK_CREATE_PROVIDER';
export const STOCK_FIND_BY_ID_PROVIDER = 'STOCK_FIND_BY_ID_PROVIDER';
export const STOCK_DELETE_PROVIDER = 'STOCK_DELETE_PROVIDER';
export const STOCK_UPDATE_PROVIDER = 'STOCK_UPDATE_PROVIDER';


export const PRODUCTS_FIND_BY_ID_PROVIDER = 'PRODUCTS_FIND_BY_ID_PROVIDER'

export const CARRINHO_CREATE_PROVIDER = 'CARRINHO_CREATE_PROVIDER';
export const CARRINHO_FIND_ITENS_BY_ID_PROVIDER = 'CARRINHO_FIND_ITENS_BY_ID_PROVIDER';

export const ITEM_CARRINHO_CREATE_PROVIDER = 'ITEM_CARRINHO_CREATE_PROVIDER';
export const ITEM_CARRINHO_FIND_ALL_BY_ID_PROVIDER = 'ITEM_CARRINHO_FIND_ALL_BY_ID_PROVIDER';

export const MOTOBOY_CREATE_PROVIDER = 'MOTOBOY_CREATE_PROVIDER';
export const MOTOBOY_FIND_ALL_PROVIDER = 'MOTOBOY_FIND_ALL_PROVIDER';
export const MOTOBOY_FIND_BY_ID_PROVIDER = 'MOTOBOY_FIND_BY_ID_PROVIDER';
export const MOTOBOY_FIND_BY_EMAIL_PROVIDER = 'MOTOBOY_FIND_BY_EMAIL_PROVIDER';
export const MOTOBOY_PROFILE_PROVIDER = 'MOTOBOY_PROFILE_PROVIDER';
export const MOTOBOY_UPDATE_PROVIDER = 'MOTOBOY_UPDATE_PROVIDER';